#!/bin/bash

export PATH="$PATH:/usr/local/bin"

function trap_ctrlc () {
	printf "\n"
	if docker ps &> /dev/null; then
		echo "[*] quitting iina..."
		osascript -e 'quit app "IINA"' &> /dev/null
		
		if docker top $name &> /dev/null; then
			echo "[*] stopping server..."
			docker stop $name &> /dev/null || true
		fi
		
		echo "[*] quitting docker..."
		if [ "$homebrew_mode" = true ]; then
			docker-machine stop default &> /dev/null
		else
			osascript -e 'quit app "Docker"' 1> /dev/null
		fi
	fi
	exit 2
}
trap "trap_ctrlc" 2

function helptext {
	scr=$(basename $0)
	echo "USAGE: ./$scr <Acestream ID>"
}

[ -z "$1" ] && helptext && exit 0

if ! ls /Applications/ | grep -qi IINA
then 
	echo "[!] Error! IINA not found, get it at https://iina.io"
	exit 1
fi

homebrew_mode=false

if ! ls /Applications/ | grep -qi Docker; then 
	if [ -x "$(docker-machine)" ]; then
		echo '[!] Error! Docker not found, get it at https://www.docker.com or with homebrew'
		exit 1
	else
		echo "[*] Detected Docker installation with homebrew (docker-machine)"
		homebrew_mode=true
	fi
else
	echo "[*] Detected desktop-based Docker installation"
fi

image="blaiseio/acelink:1.3.0"
name="acelink--ace-stream-server"
port="6878"

# remove "acestream://" from arg if found at the beginning
full=$1
prefix="acestream://"
hash=${full/#$prefix}

# Start Docker if not running
printf "[*] starting docker"
if [ "$homebrew_mode" = true ]; then
	# Assuming docker-machine is correctly set up and working
	docker-machine start default &> /dev/null
	docker-machine env default &> /dev/null
	eval $(docker-machine env default)
else
	if ! docker ps &> /dev/null; then
		open --background --hide -a Docker
	fi
fi
# Wait until Docker runs
until docker ps &> /dev/null; do
	printf "."
	sleep 0.5
done
printf "\n"
echo "[*] docker is running"

# Download Docker image if not available
if ! docker image inspect $image &> /dev/null; then
	echo "[*] pulling docker image ${image}"
	docker pull $image
fi

ip_address="127.0.0.1"
if [ "$homebrew_mode" = true ]; then
	ip_address=$(docker-machine ip)
fi

# Start Ace Stream server if not running
if ! nc -z $ip_address $port &> /dev/null; then
	printf "[*] starting Ace Stream server"
	docker run -d --rm -p $port:$port --name=$name $image 1> /dev/null

	# Wait until Ace Stream server runs
	until curl "http://${ip_address}:${port}/webui/api/service?method=get_version" &> /dev/null; do
		printf "."
		sleep 0.5
	done
	printf "\n"
fi
echo "[*] acestream server is running"

# Open stream in IINA
stream="http://$ip_address:${port}/ace/getstream?id=${hash}"
echo "[*] opening stream"
/Applications/IINA.app/Contents/MacOS/iina-cli "${stream}"

# Keep running until CTRL+C
while true
do
	sleep 10
done